apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anythingllm

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - model-storage-pvc.yaml
  - model-download-job.yaml
  - workbench.yaml
  - servingruntime.yaml
  - inferenceservice.yaml
