apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-workbench-pvc
  namespace: anythingllm
  labels:
    app: anythingllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
