# Operator Version Configuration
# This file defines available operator versions for dynamic selection
# You can add custom versions by adding entries to the versions list for each operator
# For operators not listed here, see the custom_operators section at the bottom

operators:
  openshift-gitops:
    description: "Red Hat OpenShift GitOps"
    versions:
      - name: "latest"
        channel: "latest"
        description: "Latest stable version"
      - name: "gitops-1.13"
        channel: "gitops-1.13"
        description: "GitOps 1.13"
      - name: "gitops-1.12"
        channel: "gitops-1.12"
        description: "GitOps 1.12"
      - name: "gitops-1.11"
        channel: "gitops-1.11"
        description: "GitOps 1.11"
      - name: "gitops-1.10"
        channel: "gitops-1.10"
        description: "GitOps 1.10"
      # Add custom versions here following the same format
    default: "latest"
    allow_custom: true

  openshift-ai:
    description: "Red Hat OpenShift AI"
    versions:
      - name: "stable"
        channel: "stable"
        description: "Stable channel"
      - name: "stable-2.16"
        channel: "stable-2.16"
        description: "Stable 2.16"
      - name: "eus-2.16"
        channel: "eus-2.16"
        description: "Extended Update Support 2.16"
      - name: "stable-2.13"
        channel: "stable-2.13"
        description: "Stable 2.13"
      - name: "stable-2.10"
        channel: "stable-2.10"
        description: "Stable 2.10"
      - name: "fast"
        channel: "fast"
        description: "Fast channel - latest features"
      - name: "beta"
        channel: "beta"
        description: "Beta channel - preview features"
      # Add custom versions here
    default: "stable"
    allow_custom: true

  gpu-operator:
    description: "NVIDIA GPU Operator"
    versions:
      - name: "stable"
        channel: "stable"
        description: "Stable channel (currently v25.3.3)"
      - name: "v25.3"
        channel: "v25.3"
        description: "Version 25.3"
      - name: "v24.9"
        channel: "v24.9"
        description: "Version 24.9"
      - name: "v24.6"
        channel: "v24.6"
        description: "Version 24.6"
      - name: "v23.9"
        channel: "v23.9"
        description: "Version 23.9"
      - name: "v23.6"
        channel: "v23.6"
        description: "Version 23.6"
      - name: "v23.3"
        channel: "v23.3"
        description: "Version 23.3"
      - name: "v22.9"
        channel: "v22.9"
        description: "Version 22.9"
      # Add custom versions here - e.g., v25.3.3
    default: "stable"
    allow_custom: true

  nfd:
    description: "Node Feature Discovery"
    versions:
      - name: "stable"
        channel: "stable"
        description: "Stable channel"
      - name: "4.17"
        channel: "4.17"
        description: "Version 4.17"
      - name: "4.16"
        channel: "4.16"
        description: "Version 4.16"
      - name: "4.15"
        channel: "4.15"
        description: "Version 4.15"
      # Add custom versions here
    default: "stable"
    allow_custom: true

  openshift-pipelines:
    description: "Red Hat OpenShift Pipelines"
    versions:
      - name: "latest"
        channel: "latest"
        description: "Latest stable version"
      - name: "stable"
        channel: "stable"
        description: "Stable channel"
      - name: "pipelines-1.15"
        channel: "pipelines-1.15"
        description: "Pipelines 1.15"
      - name: "pipelines-1.14"
        channel: "pipelines-1.14"
        description: "Pipelines 1.14"
      - name: "pipelines-1.13"
        channel: "pipelines-1.13"
        description: "Pipelines 1.13"
      # Add custom versions here
    default: "latest"
    allow_custom: true

  openshift-serverless:
    description: "Red Hat OpenShift Serverless"
    versions:
      - name: "stable"
        channel: "stable"
        description: "Stable channel"
      - name: "1.34"
        channel: "serverless-1.34"
        description: "Serverless 1.34"
      - name: "1.33"
        channel: "serverless-1.33"
        description: "Serverless 1.33"
      - name: "1.32"
        channel: "serverless-1.32"
        description: "Serverless 1.32"
      # Add custom versions here
    default: "stable"
    allow_custom: true

  openshift-servicemesh:
    description: "Red Hat OpenShift Service Mesh"
    versions:
      - name: "stable"
        channel: "stable"
        description: "Stable channel"
      - name: "2.6"
        channel: "stable-2.6"
        description: "Service Mesh 2.6"
      - name: "2.5"
        channel: "stable-2.5"
        description: "Service Mesh 2.5"
      - name: "2.4"
        channel: "stable-2.4"
        description: "Service Mesh 2.4"
      # Add custom versions here
    default: "stable"
    allow_custom: true

  elasticsearch:
    description: "Elasticsearch Operator"
    versions:
      - name: "stable"
        channel: "stable"
        description: "Stable channel"
      - name: "stable-5.8"
        channel: "stable-5.8"
        description: "Elasticsearch 5.8"
      - name: "stable-5.7"
        channel: "stable-5.7"
        description: "Elasticsearch 5.7"
      # Add custom versions here
    default: "stable"
    allow_custom: true

  authorino:
    description: "Authorino Operator"
    versions:
      - name: "managed-services"
        channel: "tech-preview-v1"
        description: "Tech Preview v1"
      - name: "stable"
        channel: "stable"
        description: "Stable channel"
      # Add custom versions here
    default: "managed-services"
    allow_custom: true

# Custom operators not in the predefined list
# Add your custom operators here with their configurations
custom_operators:
  # Example:
  # my-custom-operator:
  #   description: "My Custom Operator"
  #   namespace: "my-operator-namespace"
  #   path: "components/operators/my-custom-operator/aggregate/overlays/default"
  #   versions:
  #     - name: "stable"
  #       channel: "stable"
  #       description: "Stable channel"
  #   default: "stable"
EOF'
