apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anythingllm

resources:
  - ../../base

# Default model configuration
# This can be overridden by other overlays or patches
patches:
  - target:
      kind: Job
      name: model-download
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/redhat-ai-services/modelcar-catalog:qwen3-8b
  - target:
      kind: InferenceService
      name: llm-model
    patch: |-
      - op: replace
        path: /metadata/annotations/modelcar.model
        value: qwen3-8b
