kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: add-kubeadmin
  annotations:
    argocd.argoproj.io/sync-wave: "5"
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: 'kube:admin'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: rhods-admins
  annotations:
    argocd.argoproj.io/sync-wave: "5"
users:
  - kube:admin
