apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
  - datasciencecluster.yaml
  - dsc-init.yaml
  - namespace.yaml
  - odhdashboardconfig.yaml
  - rhods-role-binding.yaml
  - wait-for-operators-job.yaml
  - wait-for-crds-job.yaml
