apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redhat-ods-applications
  namespace: redhat-ods-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: odh-dashboard
    namespace: redhat-ods-applications
