apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-for-crds
  annotations:
    argocd.argoproj.io/sync-wave: "15"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wait-for-crds
  annotations:
    argocd.argoproj.io/sync-wave: "15"
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wait-for-crds
  annotations:
    argocd.argoproj.io/sync-wave: "15"
subjects:
  - kind: ServiceAccount
    name: wait-for-crds
    namespace: redhat-ods-applications
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wait-for-crds
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-crds
  annotations:
    argocd.argoproj.io/sync-wave: "16"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: wait
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for OpenShift AI CRDs to be available..."
              
              # List of required CRDs
              REQUIRED_CRDS=(
                "datascienceclusters.datasciencecluster.opendatahub.io"
                "dscinitializations.dscinitialization.opendatahub.io"
                "odhdashboardconfigs.opendatahub.io"
                "acceleratorprofiles.dashboard.opendatahub.io"
              )
              
              # Wait for each CRD
              for crd in "${REQUIRED_CRDS[@]}"; do
                echo "Checking for CRD: $crd"
                until oc get crd "$crd" &>/dev/null; do
                  echo "Waiting for CRD $crd to be created..."
                  sleep 10
                done
                echo "✓ CRD $crd is available"
              done
              
              echo "All required CRDs are available. Proceeding with instance creation."
      restartPolicy: Never
      serviceAccount: wait-for-crds
      serviceAccountName: wait-for-crds
  backoffLimit: 4
