apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfd-master
  namespace: openshift-nfd
spec:
  template:
    spec:
      containers:
      - name: nfd-master
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8082
        startupProbe:
          httpGet:
            path: /healthz
            port: 8082
