apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../operator/overlays/stable
  - ../../../instance/overlays/stable
  - ../../../../gpu-operator-certified/aggregate/overlays/default
  - ../../../../nfd/aggregate/overlays/default
