apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - secret.yaml       # For MinIO or Elasticsearch access
  - namespace.yaml    # Optional, only if not already managed globally
