apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: demo-chatbot
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mc
          image: minio/mc
          env:
            - name: MC_CONFIG_DIR
              value: /tmp/.mc
          command:
            - /bin/sh
            - -c
            - |
              echo "Setting up mc alias..."
              mc alias set myminio http://minio-service.demo-chatbot.svc.cluster.local:9000 minio minio123

              echo "Creating bucket 'demo-chatbot' if it doesn't exist..."
              mc mb -p myminio/demo-chatbot || echo "Bucket may already exist"

              echo "✅ Done"
