apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: demo-chatbot
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mc
          image: quay.io/minio/mc
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MinIO to be reachable..."
              until wget -q --spider http://minio-service.demo-chatbot.svc.cluster.local:9000/minio/health/live; do
                echo "Waiting..."
                sleep 2
              done

              echo "Setting up mc alias..."
              mc alias set myminio http://minio-service.demo-chatbot.svc.cluster.local:9000 minio minio123

              echo "Creating bucket 'demo-chatbot' if it doesn't exist..."
              mc mb -p myminio/demo-chatbot || echo "Bucket may already exist"

              echo "✅ Done"
