apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: demo-chatbot
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mc
          image: curlimages/curl
          command:
            - /bin/sh
            - -c
            - |
              echo "Installing MinIO Client (mc)..."
              curl -sLO https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc && mv mc /usr/bin/

              echo "Waiting for MinIO to be reachable..."
              until curl -s http://minio-service.demo-chatbot.svc.cluster.local:9000/minio/health/live; do
                echo "Waiting for MinIO to be live..."
                sleep 2
              done

              echo "Setting up mc alias..."
              mc alias set myminio http://minio-service.demo-chatbot.svc.cluster.local:9000 minio minio123

              echo "Creating bucket 'demo-chatbot' if it doesn't exist..."
              mc mb -p myminio/demo-chatbot || echo "Bucket may already exist"

              echo "✅ Done"
