apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-chatbot  # Ensure this namespace is created or included in resources

resources:
  - ../../../base

#patchesStrategicMerge:
#  - env-vars.yaml     # Optional: sets env vars like model URL, S3 URL
#  - tolerations.yaml  # Optional: only if chatbot pod needs GPU or taints
