apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
  - ../../base

components:
  - ../../components/components-serving
  - ../../components/idle-notebook-culling
  - ../../components/notebook-sizes-cm  # New v2.22+ compatible notebook sizes
  - ../../components/gpu-settings  # New v2.22+ compatible GPU configuration
  - ../../components/make-kubeadmin-cluster-admin
  - ../../components/rhods-admins-group
