apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: authorino-operator
          path: components/operators/authorino-operator/operator/overlays/managed-services
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: elasticsearch-operator
          path: components/operators/elasticsearch/operator/overlays/stable
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: nvidia-gpu-operator
          path: components/operators/gpu-operator-certified/instance/overlays/g5-4xlarge
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: nfd-operator
          path: components/operators/nfd/aggregate/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-ai-operator
          path: components/operators/openshift-ai/aggregate/overlays/stable-nvidia-gpu
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-gitops-operator
          path: components/operators/openshift-gitops/aggregate/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-pipelines-operator
          path: components/operators/openshift-pipelines/operator/overlays/latest
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-serverless-operator
          path: components/operators/openshift-serverless/operator/overlays/stable
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-servicemesh-operator
          path: components/operators/openshift-servicemesh/operator/overlays/stable
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-servicemesh-instance
          path: components/operators/openshift-servicemesh/instance/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: knative-serving-instance
          path: components/operators/openshift-serverless/instance/knative-serving/overlays/default
