apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: anythingllm

resources:
  - ../../base

patches:
  - target:
      kind: Job
      name: model-download
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/redhat-ai-services/modelcar-catalog:llama3.1-8b
  - target:
      kind: InferenceService
      name: llm-model
    patch: |-
      - op: replace
        path: /metadata/annotations/modelcar.model
        value: llama3.1-8b
  - target:
      kind: Notebook
      name: anythingllm-workbench
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MODEL_NAME
          value: llama3.1-8b
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: MODEL_ENDPOINT
          value: http://llm-model.anythingllm.svc.cluster.local:8080/v1
